# Generated by Django 5.2.14 on 2026-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fazendas_permitidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.fazenda'),
        ),
    ]
