# Generated by Django 5.2.15 on 2026-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0002_tipomaquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncargoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('valor', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Encargo da Folha',
                'verbose_name_plural': 'Encargos da Folha',
            },
        ),
    ]
