# Generated by Django 5.2.14 on 2026-05-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0002_proprietario_bairro_proprietario_celular_and_more'),
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoPlanejada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio_planejada', models.DateField()),
                ('data_fim_planejada', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('tipo_operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.tipooperacao')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço Planejada',
                'verbose_name_plural': 'Ordens de Serviço Planejadas',
            },
        ),
        migrations.CreateModel(
            name='ItemInsumoOSPlanejado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dose_planejada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantidade_planejada', models.DecimalField(decimal_places=4, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('ordem_servico_planejada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='planejamento.ordemservicoplanejada')),
            ],
            options={
                'verbose_name': 'Insumo da OS Planejada',
                'verbose_name_plural': 'Insumos da OS Planejada',
            },
        ),
        migrations.CreateModel(
            name='ParametroOperacionalOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('velocidade_planejada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressao_planejada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vazao_planejada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo_bico', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem_servico_planejada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='planejamento.ordemservicoplanejada')),
            ],
            options={
                'verbose_name': 'Parâmetro Operacional de OS',
                'verbose_name_plural': 'Parâmetros Operacionais de OS',
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoMaoObraTerceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('grupo_trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.grupotrabalhador')),
                ('ordem_servico_planejada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_obra_terceiros', to='planejamento.ordemservicoplanejada')),
            ],
            options={
                'verbose_name': 'Planejamento de Mão de Obra de Terceiros',
                'verbose_name_plural': 'Planejamento de Mão de Obra de Terceiros',
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoSafra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=250)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_planejamento', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos', to='core.fazenda')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos', to='core.safra')),
            ],
            options={
                'verbose_name': 'Planejamento de Safra',
                'verbose_name_plural': 'Planejamentos de Safra',
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('conta_gerencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.contagerencial')),
                ('criterio_rateio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.criteriorateio')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='planejamento.planejamentosafra')),
            ],
            options={
                'verbose_name': 'Planejamento de Rateio',
                'verbose_name_plural': 'Planejamentos de Rateio',
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoAdubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cobertura', models.IntegerField()),
                ('data_planejada', models.DateField()),
                ('dose_planejada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantidade_planejada', models.DecimalField(decimal_places=4, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.talhao')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adubacoes', to='planejamento.planejamentosafra')),
            ],
            options={
                'verbose_name': 'Planejamento de Adubação',
                'verbose_name_plural': 'Planejamentos de Adubação',
            },
        ),
        migrations.AddField(
            model_name='ordemservicoplanejada',
            name='planejamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='planejamento.planejamentosafra'),
        ),
        migrations.CreateModel(
            name='OrdemServicoPlanejadaTalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_servico_planejada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='planejamento.ordemservicoplanejada')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.talhao')),
            ],
            options={
                'verbose_name': 'Talhão da OS Planejada',
                'verbose_name_plural': 'Talhões da OS Planejada',
                'unique_together': {('ordem_servico_planejada', 'talhao', 'ativo')},
            },
        ),
    ]
