# Generated by Django 5.2.16 on 2026-07-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_locacaomaquina_data_encerramento_and_more'),
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoplanejada',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_planejadas', to='cadastros.funcionario'),
        ),
        migrations.AddField(
            model_name='ordemservicoplanejada',
            name='implemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_planejadas_implemento', to='cadastros.maquina'),
        ),
        migrations.AddField(
            model_name='ordemservicoplanejada',
            name='trator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_planejadas_trator', to='cadastros.maquina'),
        ),
    ]
