# Generated by Django 5.2.15 on 2026-07-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_locacaomaquina_data_encerramento_and_more'),
        ('planejamento', '0002_ordemservicoplanejada_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoplanejada',
            name='terceirizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_planejadas', to='cadastros.terceirizado'),
        ),
        migrations.AddField(
            model_name='ordemservicoplanejada',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_planejadas', to='cadastros.turmaterceirizada'),
        ),
    ]
