# Generated by Django 5.2.15 on 2026-07-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0003_ordemservicoplanejada_terceirizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoplanejada',
            name='valor_planejado_turma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Planejado da Turma'),
        ),
    ]
