# Generated by Django 5.2.14 on 2026-05-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0002_proprietario_bairro_proprietario_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoTalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Talhão da OS Real',
                'verbose_name_plural': 'Talões da OS Real',
            },
        ),
        migrations.CreateModel(
            name='ItemInsumoOSReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dose_planejada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quantidade_planejada', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('dose_real', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quantidade_real', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Insumo da OS Real',
                'verbose_name_plural': 'Insumos da OS Real',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('data_inicio_planejada', models.DateField()),
                ('data_fim_planejada', models.DateField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADA', 'Aprovada'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='APROVADA', max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_reais', to='core.fazenda')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
