# Generated by Django 5.2.14 on 2026-05-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0002_proprietario_bairro_proprietario_celular_and_more'),
        ('operacoes', '0001_initial'),
        ('planejamento', '0001_initial'),
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='origem_planejada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='planejamento.ordemservicoplanejada'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='safra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_reais', to='core.safra'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.tipooperacao'),
        ),
        migrations.AddField(
            model_name='iteminsumoosreal',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='operacoes.ordemservico'),
        ),
        migrations.AddField(
            model_name='ordemservicotalhao',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='operacoes.ordemservico'),
        ),
        migrations.AddField(
            model_name='ordemservicotalhao',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.talhao'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemservicotalhao',
            unique_together={('ordem_servico', 'talhao', 'ativo')},
        ),
    ]
