# Generated by Django 5.2.14 on 2026-05-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('operacoes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_apontamento', models.DateField()),
                ('clima', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='operacoes.ordemservico')),
            ],
            options={
                'verbose_name': 'Apontamento de Operação',
                'verbose_name_plural': 'Apontamentos de Operação',
            },
        ),
        migrations.CreateModel(
            name='ApontamentoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('horimetro_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horimetro_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina')),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='operacoes.apontamentooperacao')),
            ],
            options={
                'verbose_name': 'Apontamento de Máquina',
                'verbose_name_plural': 'Apontamentos de Máquina',
            },
        ),
        migrations.CreateModel(
            name='ApontamentoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dose_realizada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='operacoes.apontamentooperacao')),
            ],
            options={
                'verbose_name': 'Apontamento de Insumo',
                'verbose_name_plural': 'Apontamentos de Insumo',
            },
        ),
        migrations.CreateModel(
            name='ApontamentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('horas_trabalhadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcionario')),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='operacoes.apontamentooperacao')),
            ],
            options={
                'verbose_name': 'Apontamento de Funcionário',
                'verbose_name_plural': 'Apontamentos de Funcionário',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_desvio', models.CharField(choices=[('PRODUTO_NAO_PLANEJADO', 'Produto Não Planejado'), ('SUBDOSE', 'Subdose'), ('SUPERDOSE', 'Superdose'), ('FORA_DA_JANELA', 'Fora da Janela Planejada'), ('OUTRO', 'Outro')], max_length=50)),
                ('descricao_desvio', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Avaliação'), ('JUSTIFICADO', 'Justificado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=30)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='operacoes.ordemservico')),
            ],
            options={
                'verbose_name': 'Auditoria de Ordem de Serviço',
                'verbose_name_plural': 'Auditorias de Ordem de Serviço',
            },
        ),
    ]
