# Generated by Django 5.2.15 on 2026-06-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_maquina_tipo'),
        ('core', '0005_alter_proprietario_email'),
        ('operacoes', '0003_apontamentooperacao_apontamentomaquina_and_more'),
        ('referencias', '0002_tipomaquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbastecimentoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_abastecimento', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='core.fazenda')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='core.safra')),
            ],
            options={
                'verbose_name': 'Abastecimento de Máquina',
                'verbose_name_plural': 'Abastecimentos de Máquina',
            },
        ),
        migrations.CreateModel(
            name='GastoRateioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_gasto', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('conta_gerencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.contagerencial')),
                ('criterio_rateio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.criteriorateio')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_rateio_realizados', to='core.fazenda')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_rateio_realizados', to='core.safra')),
            ],
            options={
                'verbose_name': 'Gasto de Rateio Realizado',
                'verbose_name_plural': 'Gastos de Rateio Realizados',
            },
        ),
        migrations.CreateModel(
            name='RateioTalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gasto_rateio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios_talhoes', to='operacoes.gastorateiorealizado')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.talhao')),
            ],
            options={
                'verbose_name': 'Rateio por Talhão',
                'verbose_name_plural': 'Rateios por Talhão',
                'unique_together': {('gasto_rateio', 'talhao', 'ativo')},
            },
        ),
    ]
