# Generated by Django 5.2.15 on 2026-06-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_maquina_tipo'),
        ('core', '0005_alter_proprietario_email'),
        ('operacoes', '0004_abastecimentomaquina_gastorateiorealizado_and_more'),
        ('referencias', '0002_tipomaquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateioOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('descricao_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('horas_homem_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_hora_homem_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_homem_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('horas_maq_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_hora_maq_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_maq_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diesel_gasto_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_diesel_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_diesel_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qtd_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_unitario_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_plan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('descricao_real', models.CharField(blank=True, max_length=255, null=True)),
                ('horas_homem_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_hora_homem_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_homem_real', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('horas_maq_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_hora_trator_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_hora_implemento_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_maq_real', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diesel_gasto_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_diesel_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_diesel_real', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qtd_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_unitario_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total_real', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('atividade_educampo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.atividadeeducampo')),
                ('combustivel_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combustivel_plan_rateios', to='cadastros.produto')),
                ('combustivel_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combustivel_real_rateios', to='cadastros.produto')),
                ('fazenda_rateio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_operacionais', to='core.fazenda')),
                ('funcionario_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_plan_rateios', to='cadastros.funcionario')),
                ('funcionario_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_real_rateios', to='cadastros.funcionario')),
                ('implemento_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemento_plan_rateios', to='cadastros.maquina')),
                ('implemento_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemento_real_rateios', to='cadastros.maquina')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_operacionais', to='core.safra')),
                ('trator_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trator_plan_rateios', to='cadastros.maquina')),
                ('trator_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trator_real_rateios', to='cadastros.maquina')),
            ],
            options={
                'verbose_name': 'Rateio Operacional',
                'verbose_name_plural': 'Rateios Operacionais',
            },
        ),
    ]
