# Generated by Django 5.2.15 on 2026-07-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_terceirizado_cargo'),
        ('financeiro', '0003_alter_pedidocompra_fornecedor'),
        ('operacoes', '0005_rateiooperacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento para o Contas a Pagar')),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='operacoes.apontamentooperacao')),
                ('contas_a_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamento_turma', to='financeiro.contasapagar')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turmaterceirizada')),
            ],
            options={
                'verbose_name': 'Apontamento de Turma Terceirizada',
                'verbose_name_plural': 'Apontamentos de Turmas Terceirizadas',
            },
        ),
    ]
