# Generated by Django 5.2.16 on 2026-07-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_locacaomaquina_data_encerramento_and_more'),
        ('operacoes', '0006_apontamentoturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='funcionario_planejado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_plan', to='cadastros.funcionario'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='implemento_planejado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_implemento_plan', to='cadastros.maquina'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='trator_planejado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_trator_plan', to='cadastros.maquina'),
        ),
    ]
