# Generated by Django 5.2.15 on 2026-07-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_locacaomaquina_data_encerramento_and_more'),
        ('operacoes', '0007_ordemservico_funcionario_planejado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='terceirizado_planejado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_terceirizado_plan', to='cadastros.terceirizado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='turma_planejada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_turma_plan', to='cadastros.turmaterceirizada'),
        ),
    ]
