# Generated by Django 5.2.15 on 2026-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0009_ordemservico_valor_planejado_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='usar_turma',
            field=models.BooleanField(default=False, verbose_name='Usar Turma'),
        ),
    ]
