# Generated by Django 5.2.15 on 2026-08-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0010_ordemservico_usar_turma'),
        ('referencias', '0003_encargofolha'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiooperacional',
            name='criterio_rateio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rateios_operacionais', to='referencias.criteriorateio'),
        ),
    ]
