# Generated by Django 5.2.14 on 2026-05-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0002_proprietario_bairro_proprietario_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('fornecedor', models.CharField(max_length=255)),
                ('data_pedido', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=30)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.fazenda')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.safra')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.pedidocompra')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens do Pedido de Compra',
            },
        ),
        migrations.CreateModel(
            name='ContasAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=30)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='core.fazenda')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='core.safra')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_a_pagar', to='financeiro.pedidocompra')),
            ],
            options={
                'verbose_name': 'Contas a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
    ]
