# Generated by Django 5.2.14 on 2026-05-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proprietario_bairro_proprietario_celular_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.CharField(max_length=255)),
                ('data_venda', models.DateField()),
                ('tipo_produto', models.CharField(choices=[('CAFE', 'Café'), ('CEREAIS', 'Cereais'), ('SUCATA', 'Sucata'), ('OUTROS', 'Outros')], max_length=50)),
                ('quantidade_sacas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADO', 'Confirmado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=30)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='core.fazenda')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='core.safra')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
            },
        ),
        migrations.CreateModel(
            name='ContasAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria_receita', models.CharField(choices=[('VENDA_CAFE', 'Venda Café'), ('CEREAIS', 'Cereais'), ('SUCATA', 'Sucata'), ('CUSTEIO_AGRICOLA', 'Custeio Agrícola'), ('OUTROS', 'Outros')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=30)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_receber', to='core.fazenda')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_receber', to='core.safra')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_a_receber', to='financeiro.pedidovenda')),
            ],
            options={
                'verbose_name': 'Contas a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
    ]
