# Generated by Django 5.2.14 on 2026-07-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_fornecedor'),
        ('financeiro', '0002_pedidovenda_contasareceber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='cadastros.fornecedor'),
        ),
    ]
