# Generated by Django 5.2.15 on 2026-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_pedidocompra_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='de_planejamento',
            field=models.BooleanField(default=False),
        ),
    ]
