# Generated by Django 5.2.14 on 2026-05-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_proprietario_bairro_proprietario_celular_and_more'),
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='core.fazenda')),
                ('grupo_trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.grupotrabalhador')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='core.fazenda')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.tipoitem')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'unique_together': {('fazenda', 'codigo', 'ativo')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nome_comercial', models.CharField(max_length=150)),
                ('concentracao', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo_carencia', models.IntegerField(blank=True, null=True)),
                ('alvo', models.CharField(blank=True, max_length=255, null=True)),
                ('recomendacoes_tecnicas', models.TextField(blank=True, null=True)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.classificacaoproduto')),
                ('grupo_quimico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referencias.grupoquimico')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.unidademedida')),
            ],
            options={
                'verbose_name': 'Produto/Insumo',
                'verbose_name_plural': 'Produtos/Insumos',
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_movimento', models.DateField()),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('destino_transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='core.fazenda')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='core.fazenda')),
                ('origem_transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='core.fazenda')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='core.safra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espacamento_rua', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('espacamento_planta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estande', models.IntegerField(blank=True, null=True)),
                ('numero_plantas', models.IntegerField(blank=True, null=True)),
                ('material_genetico', models.CharField(blank=True, max_length=150, null=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.cultura')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talhoes', to='core.fazenda')),
                ('resistencia_ferrugem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referencias.resistenciaferrugem')),
                ('status_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referencias.statuscultivo')),
                ('tipo_irrigacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.tipoirrigacao')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
                'unique_together': {('fazenda', 'codigo', 'ativo')},
            },
        ),
        migrations.CreateModel(
            name='Terceirizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceirizados', to='core.fazenda')),
            ],
            options={
                'verbose_name': 'Terceirizado',
                'verbose_name_plural': 'Terceirizados',
            },
        ),
        migrations.CreateModel(
            name='TurmaTerceirizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas_terceirizadas', to='core.fazenda')),
                ('integrantes', models.ManyToManyField(blank=True, related_name='turmas', to='cadastros.terceirizado')),
            ],
            options={
                'verbose_name': 'Turma Terceirizada',
                'verbose_name_plural': 'Turmas Terceirizadas',
            },
        ),
        migrations.CreateModel(
            name='CustoMensalMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('custo_oficina', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('custo_abastecimento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_maquinas', to='core.safra')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_mensais', to='cadastros.maquina')),
            ],
            options={
                'verbose_name': 'Custo Mensal de Máquina',
                'verbose_name_plural': 'Custos Mensais de Máquinas',
                'unique_together': {('maquina', 'safra', 'mes', 'ano', 'ativo')},
            },
        ),
        migrations.CreateModel(
            name='SalarioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('encargos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('beneficios', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salarios', to='cadastros.funcionario')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salarios_funcionarios', to='core.safra')),
            ],
            options={
                'verbose_name': 'Salário Mensal',
                'verbose_name_plural': 'Salários Mensais',
                'unique_together': {('funcionario', 'safra', 'mes', 'ano', 'ativo')},
            },
        ),
        migrations.CreateModel(
            name='EstimativaProducaoTalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('estimativa_sacas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtividade_esperada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimativas_talhoes', to='core.safra')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimativas', to='cadastros.talhao')),
            ],
            options={
                'verbose_name': 'Estimativa de Produção',
                'verbose_name_plural': 'Estimativas de Produção',
                'unique_together': {('talhao', 'safra', 'ativo')},
            },
        ),
    ]
