# Generated by Django 5.2.14 on 2026-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_funcionario_criar_usuario_funcionario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmaterceirizada',
            name='qtd_pessoas',
            field=models.IntegerField(default=0),
        ),
    ]
