# Generated by Django 5.2.15 on 2026-06-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_turmaterceirizada_qtd_pessoas'),
        ('referencias', '0002_tipomaquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.tipomaquina'),
        ),
    ]
