# Generated by Django 5.2.14 on 2026-06-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_maquina_tipo'),
        ('core', '0005_alter_proprietario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.fazenda'),
        ),
        migrations.AddField(
            model_name='produto',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.safra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('fazenda', 'safra', 'codigo', 'ativo')},
        ),
    ]
