# Generated by Django 5.2.14 on 2026-06-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_produto_fazenda_produto_safra_alter_produto_codigo_and_more'),
        ('core', '0005_alter_proprietario_email'),
        ('financeiro', '0002_pedidovenda_contasareceber'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquemovimento',
            name='transferencia_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos', to='cadastros.estoquemovimento'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='propria',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LocacaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_cobranca', models.CharField(choices=[('DIA', 'Diária'), ('HORA', 'Hora'), ('MES', 'Mês'), ('OUTRO', 'Outro')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_vencimento', models.DateField(help_text='Data de vencimento para o Contas a Pagar')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('contas_a_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locacao_maquina', to='financeiro.contasapagar')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='core.fazenda')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='cadastros.maquina')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='core.safra')),
            ],
            options={
                'verbose_name': 'Locação de Máquina',
                'verbose_name_plural': 'Locações de Máquinas',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_ativo', models.CharField(choices=[('MAQUINA', 'Máquina'), ('FUNCIONARIO', 'Funcionário')], max_length=20)),
                ('data_transferencia', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_ativos_recebidas', to='core.fazenda')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='cadastros.funcionario')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='cadastros.maquina')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_ativos_enviadas', to='core.fazenda')),
            ],
            options={
                'verbose_name': 'Transferência de Ativo',
                'verbose_name_plural': 'Transferências de Ativos',
            },
        ),
    ]
