# Generated by Django 5.2.14 on 2026-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_estoquemovimento_transferencia_vinculada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='horimetro_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Horímetro inicial no cadastro da máquina', max_digits=10),
        ),
    ]
