# Generated by Django 5.2.14 on 2026-06-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_maquina_horimetro_inicial'),
        ('core', '0005_alter_proprietario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='cadastros.maquina')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='core.safra')),
            ],
            options={
                'verbose_name': 'Manutenção de Máquina',
                'verbose_name_plural': 'Manutenções de Máquinas',
            },
        ),
    ]
