# Generated by Django 5.2.14 on 2026-06-25 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_manutencaomaquina'),
        ('financeiro', '0002_pedidovenda_contasareceber'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaomaquina',
            name='contas_a_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_maquina', to='financeiro.contasapagar'),
        ),
    ]
