# Generated by Django 5.2.14 on 2026-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_manutencaomaquina_contas_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaomaquina',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento para o Contas a Pagar', null=True),
        ),
        migrations.AddField(
            model_name='manutencaomaquina',
            name='nota_fiscal',
            field=models.CharField(blank=True, help_text='Número da Nota Fiscal', max_length=50, null=True),
        ),
    ]
