# Generated by Django 5.2.15 on 2026-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_manutencaomaquina_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='terceirizado',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
