# Generated by Django 5.2.15 on 2026-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_funcionario_salario_terceirizado_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='encargos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='terceirizado',
            name='encargos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
