# Generated by Django 5.2.15 on 2026-07-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_terceirizado_cargo'),
        ('referencias', '0003_encargofolha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacaomaquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='referencias.tipomaquina'),
        ),
    ]
