# Generated by Django 5.2.15 on 2026-07-08 12:10

from django.db import migrations, models


def encerrar_locacoes_financeiras_existentes(apps, schema_editor):
    LocacaoMaquina = apps.get_model('cadastros', 'LocacaoMaquina')
    LocacaoMaquina.objects.filter(contas_a_pagar__isnull=False).update(
        status='ENCERRADA',
        quantidade_final=models.F('quantidade'),
        valor_final=models.F('valor_total'),
        data_encerramento=models.F('data_fim'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_locacaomaquina_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacaomaquina',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacaomaquina',
            name='prorrogacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locacaomaquina',
            name='quantidade_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locacaomaquina',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='locacaomaquina',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='locacaomaquina',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento definida ao encerrar a locação', null=True),
        ),
        migrations.AlterField(
            model_name='locacaomaquina',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade prevista de dias, horas ou meses', max_digits=10, null=True),
        ),
        migrations.RunPython(encerrar_locacoes_financeiras_existentes, migrations.RunPython.noop),
    ]
