# Generated by Django 5.2.15 on 2026-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_locacaomaquina_data_encerramento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='mes_ano_cultivo',
            field=models.CharField(blank=True, help_text='Mês/Ano de Cultivo (MM/AAAA)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='area',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
