# Generated by Django 5.2.15 on 2026-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_talhao_mes_ano_cultivo_alter_talhao_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
