# Generated by Django 5.2.14 on 2026-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proprietario_bairro_proprietario_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='cnpj_ou_produtor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
