# Generated by Django 5.2.14 on 2026-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fazenda_cidade_fazenda_cnpj_ou_produtor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
