# Generated by Django 5.2.14 on 2026-06-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fazenda_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
