# Generated by Django 5.2.15 on 2026-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_proprietario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='data_ultimo_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
